language: php

env:
  global:
    - EXT_NAME=data

matrix:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION=master
  include:
    - php: 5.3
      env: TYPO3_VERSION=TYPO3_6-2
    - php: 5.5
      env: TYPO3_VERSION=TYPO3_6-2
    - php: 5.5
      env: TYPO3_VERSION=master

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version
  - git config --global user.name "Oliver Hader"
  - git config --global user.email "oliver.hader@typo3.org"

before_script:
  - export TYPO3_PATH=$HOME/.Build
  - export EXT_PATH=$TYPO3_PATH/typo3conf/ext
  - >
    mkdir -p $TYPO3_PATH;
    mkdir -p $EXT_PATH/$EXT_NAME;
    cp -r . $EXT_PATH/$EXT_NAME;
  - >
    cd $TYPO3_PATH;
    git clone -q --single-branch -b $TYPO3_VERSION git://git.typo3.org/Packages/TYPO3.CMS.git typo3_src;
    ln -s typo3_src/index.php index.php;
    ln -s typo3_src/typo3 typo3;
    cd typo3_src;
    composer install -o;
    if [ "$TYPO3_VERSION" == "TYPO3_6-2" ]; then
      git fetch https://review.typo3.org/Packages/TYPO3.CMS refs/changes/51/44351/1 && git cherry-pick FETCH_HEAD;
      git fetch https://review.typo3.org/Packages/TYPO3.CMS refs/changes/32/44232/3 && git cherry-pick FETCH_HEAD;
    elif [ "$TYPO3_VERSION" == "master" ]; then
      git fetch https://review.typo3.org/Packages/TYPO3.CMS refs/changes/50/44350/1 && git cherry-pick FETCH_HEAD;
      git fetch https://review.typo3.org/Packages/TYPO3.CMS refs/changes/54/44354/2 && git cherry-pick FETCH_HEAD;
    fi
  - >
    cd $TYPO3_PATH;
    echo;
    echo "Initialized";

script:
  - >
    echo;
    echo "Running php lint";
    find "$EXT_PATH/$EXT_NAME" -name '*.php' | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    echo "Running functional test suite";
    $TYPO3_PATH/typo3_src/bin/phpunit --colors -c $EXT_PATH/$EXT_NAME/Build/FunctionalTests.xml;
